language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
stages:
- lint
- test
- analysis
- build
- deploy
lint:
  stage: lint
  script: npm run lint
test:
  stage: test
  script: npm test
analysis:
  stage: analysis
  script:
  - npm run test:coverage
  - npm run plato
after_success:
- npm run build
- npm run deploy